# Generated by Django 3.1.4 on 2020-12-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworktable",
            name="create_by",
            field=models.CharField(default="Unknown Teacher", max_length=200),
        ),
    ]
