# Generated by Django 3.1.4 on 2020-12-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_homeworktable_create_by"),
    ]

    operations = [
        migrations.RemoveField(model_name="teacherstable", name="homework_done",),
    ]
