# Generated by Django 3.1.4 on 2020-12-27 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_remove_teacherstable_homework_done"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworksDone",
            fields=[
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="task.homeworktable",
                    ),
                ),
                ("done_by", models.TextField()),
                ("create_by", models.CharField(max_length=200)),
            ],
        ),
    ]
