# Generated by Django 3.1.4 on 2020-12-27 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_homeworksdone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeworkresulttable",
            name="homework",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="task.homeworktable"
            ),
        ),
    ]
